services:
  app:
    build: .
    ports:
      - "3001:3000" 
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: "Pepper'sCoffee"
      POSTGRES_PASSWORD: "Pepper'sCoffee"
      POSTGRES_DB: "Pepper'sCoffee"
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  db-data:
