# Retrieve all coffees
GET http://localhost:3000/api/coffees
Accept: application/json

###

# Retrieve a coffee by ID
GET http://localhost:3000/api/coffees/4
Accept: application/json

###

# Create a new coffee
POST http://localhost:3000/api/coffees
Content-Type: application/json

{
  "name": "Espresso",
  "description": "Strong and bold coffee",
  "reference": "ESP123456",
  "origin_country": "Italy",
  "price_per_kg": 15.50,
  "available": true,
  "category_id": 2
}

###

# Update an existing coffee
PUT http://localhost:3000/api/coffees/4
Content-Type: application/json

{
  "price_per_kg": 16.00,
  "available": false
}

###

# Delete a coffee
DELETE http://localhost:3000/api/coffees/2
Accept: application/json