# Retrieve all order items
GET http://localhost:3000/api/order-items
Accept: application/json

###

# Retrieve an order item by ID
GET http://localhost:3000/api/order-items/1
Accept: application/json

###

# Create a new order item
POST http://localhost:3000/api/order-items
Content-Type: application/json

{
  "order_id": 1,
  "coffee_id": 3,
  "quantity": 2
}

###

# Update an existing order item
PUT http://localhost:3000/api/order-items/1
Content-Type: application/json

{
  "quantity": 5
}

###

# Delete an order item
DELETE http://localhost:3000/api/order-items/1
Accept: application/json